# Generated by Django 5.0.6 on 2024-07-24 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='othername',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
