# Generated by Django 5.0.6 on 2024-07-29 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_othername'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usergroup',
            old_name='group',
            new_name='title',
        ),
    ]
