# Generated by Django 5.0.6 on 2024-08-15 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_rename_group_usergroup_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.department'),
            preserve_default=False,
        ),
    ]
