# Generated by Django 3.2.7 on 2024-07-16 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20240715_1307'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Category'},
        ),
        migrations.AlterModelOptions(
            name='details',
            options={'verbose_name_plural': 'Details'},
        ),
        migrations.AlterModelOptions(
            name='meal',
            options={'verbose_name_plural': 'Meal'},
        ),
        migrations.AlterModelOptions(
            name='request',
            options={'verbose_name_plural': 'Request'},
        ),
    ]
