# Generated by Django 5.0.6 on 2024-07-23 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20240716_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='meals_image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='meal_image'),
        ),
    ]
