# Generated by Django 4.0.5 on 2024-09-04 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_roster'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Details',
            new_name='RequestDetails',
        ),
    ]
