# Generated by Django 5.0.6 on 2024-09-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_requestdetails_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Decline', 'Decline')], default='Pending', max_length=8),
        ),
    ]
