# Generated by Django 5.1.3 on 2024-11-20 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
