# Generated by Django 5.1.3 on 2025-01-20 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_meal_date_created_requestdetails_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestdetails',
            name='meal_price',
            field=models.CharField(default=1, max_length=7),
            preserve_default=False,
        ),
    ]
