# Generated by Django 5.1.3 on 2025-01-20 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_requestdetails_meal_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestdetails',
            name='meal_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
