# Generated by Django 5.1.3 on 2025-01-21 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_meal_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='total_price',
        ),
    ]
